// <auto-generated />
namespace WebApplication3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class qwerty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qwerty));
        
        string IMigrationMetadata.Id
        {
            get { return "202001050000574_qwerty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
